# config.ini

# ---- Communication ----
com_port=1 # Default to COM1, change based on device manager
oms_dll=68SERMC.DLL

# ---- Paths ----
teleapi_dll=E:\VSCode Projects\Observatory Code Conversion\GVO-Conversion\GVO Code C++ v1\teleapi.dll
#teleapi_dll=teleapi.dll

# ---- Tracking / motion ----
TrkRate=500.6
RAFact=120000

# ---- Location ----
C_Lat=38.5
C_Long=-106.9

# ---- Slew speeds ----
xvlslew=75000
yvlslew=50000

# ---- Debug ----
verbose=1